### PR TITLE
Site visit

### PR DESCRIPTION
**Pull request by Kavita539**
1.Refactored cart Management code and made it responsive.
2.Refactored index navbar
3.Customized logo and its color
4. Updated product list

### CODE REVIEW

**Review by ashishnnnnn — APPROVED** [review]
Code seems perfect and ui also looks responsive :+1:

**Review by amarphule — CHANGES_REQUESTED** [review]
Good job @Kavita539 , cod looks well structured one thing to add on that can you change the gray color a little bit dark, right now it's not clearly visible see
kv

**Comment by Kavita539** [comment]
> Good job @Kavita539 , cod looks well structured one thing to add on that can you change the gray color a little bit dark, right now it's not clearly visible see kv

ok will do!

**Review by amarphule — APPROVED** [review]
Looks good now

**Pull request merged**
